on: [push]

jobs:
  run_api_test:
    runs-on: ubuntu-latest
    name: Execute RapidAPI API Tests
    steps:
      - name: Execute Tests
        id: tstExec
        uses: RapidAPI/gh-api-testing-trigger@master
        with:
          test: 'test_32343438-8208-4b3f-b977-7c5652666631'
          location: 'AWS-US-WEST-2'
          environment: 'enviroment_e19eca0d-2347-4184-beeb-bf44b9543a8e'
      - name: Show Results
        run: echo "The test took ${{ steps.tstExec.outputs.time }}ms to run"; echo "The test result was ${{ steps.tstExec.outputs.succesful }}"; echo "View Report - {{ steps.tstExec.outputs.reportUrl }}"
